author:
  email: dakila@email.unc.edu
  name: Dakila Ledesma
  url: https://github.com/dakilaledesma
baseurl: ''
description: A site that reports my every work-related doing, like an automatic diary.
  Maybe it will be useful by the time I have to enumerate everything that I have done
  in my Ph.D. dissertation. My <a href="https://github.com/dakilaledesma" target="_blank">GitHub</a>.
google_analytics_id: null
paginate: 3
permalink: pretty
plugins:
- jekyll-paginate
tagline: ''
title: daxtracker.
url: https://dakilaledesma.github.io
version: 0.1.538
